"""add scheduled_purge_at to users

Revision ID: 299f5933ebfa
Revises: c714202d0647
Create Date: 2026-03-26 17:08:15.165454
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '299f5933ebfa'
down_revision: Union[str, None] = 'c714202d0647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcm_tokens_archive')
    op.drop_table('custom_trackers_archive')
    op.drop_table('logs_archive')
    op.drop_table('users_archive')
    op.add_column('users', sa.Column('scheduled_purge_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('users_firebase_uid_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_firebase_uid_key', 'users', ['firebase_uid'])
    op.drop_column('users', 'scheduled_purge_at')
    op.create_table('users_archive',
    sa.Column('uid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('enabled_trackers', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('units', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('notification_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('onboarded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('logs_archive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users_archive.uid'], name='logs_uid_fkey'),
    sa.PrimaryKeyConstraint('id', name='logs_pkey'),
    sa.UniqueConstraint('uid', 'date', name='logs_uid_date_key')
    )
    op.create_table('custom_trackers_archive',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_goal', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users_archive.uid'], name='custom_trackers_uid_fkey'),
    sa.PrimaryKeyConstraint('id', name='custom_trackers_pkey')
    )
    op.create_table('fcm_tokens_archive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users_archive.uid'], name='fcm_tokens_uid_fkey'),
    sa.PrimaryKeyConstraint('id', name='fcm_tokens_pkey'),
    sa.UniqueConstraint('uid', 'token', name='fcm_tokens_uid_token_key')
    )
    # ### end Alembic commands ###
